# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseMVVMRAC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BaseMVVMRAC

    pod 'Reveal-SDK', :git => 'https://git.coding.net/kakukeme/Reveal-SDK.git', :configurations => ['Debug']

    pod 'IQKeyboardManager', '3.2.0.3'
    pod 'Reachability'


    pod 'Appirater', '2.0.5'
    
    pod 'ReactiveObjC'
    
    pod 'Masonry'
    
    pod 'AFNetworking', '~> 3.0'

    pod 'MBProgressHUD', '~> 1.1.0'
    
    pod 'DZNEmptyDataSet'

end
